"""Swift inference code generation for Core ML models.

Reads the Core ML model spec to understand inputs/outputs, then generates
production-ready Swift files that users can drop into an Xcode project.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import coremltools as ct

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Model spec introspection
# ---------------------------------------------------------------------------


def _sanitize_swift_name(name: str) -> str:
    """Convert a raw model name into a valid Swift identifier (PascalCase)."""
    # Strip extension and path
    name = Path(name).stem
    # Replace non-alphanumeric chars with underscores
    name = re.sub(r"[^a-zA-Z0-9]", "_", name)
    # PascalCase: split on underscores and capitalize each word
    parts = [p for p in name.split("_") if p]
    if not parts:
        return "Model"
    return "".join(p[0].upper() + p[1:] for p in parts)


def _load_spec(coreml_path: str) -> Any:
    """Load the Core ML model spec without loading weights."""
    model = ct.models.MLModel(coreml_path, skip_model_load=True)
    return model.get_spec()


def _describe_input(feature: Any) -> dict[str, Any]:
    """Extract input metadata from a feature description proto."""
    info: dict[str, Any] = {"name": feature.name}
    ftype = feature.type

    if ftype.HasField("imageType"):
        img = ftype.imageType
        info["kind"] = "image"
        info["width"] = img.width
        info["height"] = img.height
        # colorSpace: 10=RGB, 20=BGR, 30=GRAYSCALE
        info["channels"] = 1 if img.colorSpace == 30 else 3
    elif ftype.HasField("multiArrayType"):
        ma = ftype.multiArrayType
        info["kind"] = "multiarray"
        info["shape"] = list(ma.shape)
        # dataType: 65568=FLOAT32, 65552=FLOAT16, 131104=INT32
        info["dtype"] = "Float32"
    else:
        info["kind"] = "unknown"
    return info


def _describe_output(feature: Any) -> dict[str, Any]:
    """Extract output metadata from a feature description proto."""
    info: dict[str, Any] = {"name": feature.name}
    ftype = feature.type

    if ftype.HasField("multiArrayType"):
        ma = ftype.multiArrayType
        info["kind"] = "multiarray"
        info["shape"] = list(ma.shape)
    elif ftype.HasField("imageType"):
        info["kind"] = "image"
    elif ftype.HasField("dictionaryType"):
        info["kind"] = "dictionary"
    else:
        info["kind"] = "unknown"
    return info


def _has_nms_stripped(recipe_results: list[Any] | None) -> bool:
    """Check if NMS was stripped during conversion."""
    if not recipe_results:
        return False
    for r in recipe_results:
        name = getattr(r, "recipe_name", "") if hasattr(r, "recipe_name") else str(r)
        if "nms" in name.lower() or "detection_unwrap" in name.lower():
            return True
    return False


# ---------------------------------------------------------------------------
# Swift template: Predictor (image input)
# ---------------------------------------------------------------------------

_PREDICTOR_IMAGE_TEMPLATE = """\
import CoreML
import Vision
import UIKit

/// Auto-generated by Model2Mobile
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let results = try predictor.predict(image: uiImage)
///
/// Requirements:
///   - Add {model_name}.mlpackage to your Xcode project
///   - iOS 15.0+ / macOS 12.0+
class {class_name}Predictor {{

    // MARK: - Properties

    private let model: MLModel

    /// Input image will be resized to this dimension.
    let inputWidth: Int = {input_width}
    let inputHeight: Int = {input_height}

    // MARK: - Initialization

    /// Load the Core ML model with the specified compute units.
    /// - Parameter computeUnits: Which hardware to run inference on (default: `.all`).
    init(computeUnits: MLComputeUnits = .all) throws {{
        let config = MLModelConfiguration()
        config.computeUnits = computeUnits

        // Load the compiled model from the app bundle.
        // Make sure {model_name}.mlpackage is added to your Xcode target.
        guard let modelURL = Bundle.main.url(
            forResource: "{model_name}",
            withExtension: "mlmodelc"
        ) else {{
            throw PredictorError.modelNotFound("{model_name}.mlmodelc")
        }}
        self.model = try MLModel(contentsOf: modelURL, configuration: config)
    }}

    // MARK: - Prediction

    /// Run inference on a UIImage.
    /// - Parameter image: The input image (any size; will be resized automatically).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(image: UIImage) throws -> {output_return_type} {{
        guard let cgImage = image.cgImage else {{
            throw PredictorError.invalidImage
        }}

        let pixelBuffer = try createPixelBuffer(from: cgImage)
        return try predict(pixelBuffer: pixelBuffer)
    }}

    /// Run inference on a CVPixelBuffer.
    /// - Parameter pixelBuffer: A pixel buffer sized to (inputWidth x inputHeight).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(pixelBuffer: CVPixelBuffer) throws -> {output_return_type} {{
        let input = try MLDictionaryFeatureProvider(
            dictionary: ["{input_name}": MLFeatureValue(pixelBuffer: pixelBuffer)]
        )

        let output = try model.prediction(from: input)
        return try parseOutput(output)
    }}

    // MARK: - Preprocessing

    /// Resize a CGImage and convert it to a CVPixelBuffer suitable for the model.
    private func createPixelBuffer(from cgImage: CGImage) throws -> CVPixelBuffer {{
        var pixelBuffer: CVPixelBuffer?
        let attrs: [String: Any] = [
            kCVPixelBufferCGImageCompatibilityKey as String: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey as String: true,
        ]

        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            inputWidth,
            inputHeight,
            kCVPixelFormatType_32BGRA,
            attrs as CFDictionary,
            &pixelBuffer
        )

        guard status == kCVReturnSuccess, let buffer = pixelBuffer else {{
            throw PredictorError.pixelBufferCreationFailed
        }}

        CVPixelBufferLockBaseAddress(buffer, [])
        defer {{ CVPixelBufferUnlockBaseAddress(buffer, []) }}

        guard let context = CGContext(
            data: CVPixelBufferGetBaseAddress(buffer),
            width: inputWidth,
            height: inputHeight,
            bitsPerComponent: 8,
            bytesPerRow: CVPixelBufferGetBytesPerRow(buffer),
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue
                | CGBitmapInfo.byteOrder32Little.rawValue
        ) else {{
            throw PredictorError.pixelBufferCreationFailed
        }}

        // Draw the image scaled to the model's expected input size
        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: inputWidth, height: inputHeight))

        return buffer
    }}

    // MARK: - Output parsing

    private func parseOutput(_ output: MLFeatureProvider) throws -> {output_return_type} {{
{output_parsing_body}
    }}
}}

// MARK: - Errors

enum PredictorError: LocalizedError {{
    case modelNotFound(String)
    case invalidImage
    case pixelBufferCreationFailed
    case outputMissing(String)
    case multiArrayCreationFailed

    var errorDescription: String? {{
        switch self {{
        case .modelNotFound(let name):
            return "Core ML model not found in bundle: \\(name)"
        case .invalidImage:
            return "Could not extract CGImage from the provided UIImage"
        case .pixelBufferCreationFailed:
            return "Failed to create CVPixelBuffer for model input"
        case .outputMissing(let name):
            return "Expected output '\\(name)' not found in model prediction"
        case .multiArrayCreationFailed:
            return "Failed to create MLMultiArray for model input"
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: Predictor (multiarray input)
# ---------------------------------------------------------------------------

_PREDICTOR_MULTIARRAY_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let inputArray: MLMultiArray = ...  // shape: {input_shape_comment}
///   let results = try predictor.predict(input: inputArray)
///
/// Requirements:
///   - Add {model_name}.mlpackage to your Xcode project
///   - iOS 15.0+ / macOS 12.0+
class {class_name}Predictor {{

    // MARK: - Properties

    private let model: MLModel

    /// Expected input shape: {input_shape_comment}
    let inputShape: [Int] = {input_shape_literal}

    // MARK: - Initialization

    /// Load the Core ML model with the specified compute units.
    /// - Parameter computeUnits: Which hardware to run inference on (default: `.all`).
    init(computeUnits: MLComputeUnits = .all) throws {{
        let config = MLModelConfiguration()
        config.computeUnits = computeUnits

        guard let modelURL = Bundle.main.url(
            forResource: "{model_name}",
            withExtension: "mlmodelc"
        ) else {{
            throw PredictorError.modelNotFound("{model_name}.mlmodelc")
        }}
        self.model = try MLModel(contentsOf: modelURL, configuration: config)
    }}

    // MARK: - Prediction

    /// Run inference on an MLMultiArray input.
    /// - Parameter input: Multi-dimensional array matching the expected input shape.
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(input: MLMultiArray) throws -> {output_return_type} {{
        let featureValue = MLFeatureValue(multiArray: input)
        let inputProvider = try MLDictionaryFeatureProvider(
            dictionary: ["{input_name}": featureValue]
        )

        let output = try model.prediction(from: inputProvider)
        return try parseOutput(output)
    }}

    /// Convenience: run inference from a UIImage by converting it to a normalized tensor.
    /// - Parameter image: The input image (will be resized to model input dimensions).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(image: UIImage) throws -> {output_return_type} {{
        let inputArray = try imageToMultiArray(image)
        return try predict(input: inputArray)
    }}

    // MARK: - Image to MLMultiArray conversion

    /// Convert a UIImage to a normalized MLMultiArray [1, C, H, W].
    private func imageToMultiArray(_ image: UIImage) throws -> MLMultiArray {{
        guard inputShape.count == 4 else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        let channels = inputShape[1]
        let height = inputShape[2]
        let width = inputShape[3]

        guard let cgImage = image.cgImage else {{
            throw PredictorError.invalidImage
        }}

        // Render the image into a raw RGBA byte buffer
        let bytesPerPixel = 4
        let bytesPerRow = bytesPerPixel * width
        var rawBytes = [UInt8](repeating: 0, count: height * bytesPerRow)

        guard let context = CGContext(
            data: &rawBytes,
            width: width,
            height: height,
            bitsPerComponent: 8,
            bytesPerRow: bytesPerRow,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: width, height: height))

        // Create the MLMultiArray in NCHW layout
        let shape = inputShape.map {{ NSNumber(value: $0) }}
        guard let array = try? MLMultiArray(shape: shape, dataType: .float32) else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        // Fill: normalize pixel values to [0, 1]
        let channelCount = min(channels, 3)
        for c in 0..<channelCount {{
            for y in 0..<height {{
                for x in 0..<width {{
                    let pixelIndex = y * width + x
                    let byteOffset = pixelIndex * bytesPerPixel + c  // R=0, G=1, B=2
                    let value = Float(rawBytes[byteOffset]) / 255.0
                    let arrayIndex = c * height * width + y * width + x
                    array[arrayIndex] = NSNumber(value: value)
                }}
            }}
        }}

        return array
    }}

    // MARK: - Output parsing

    private func parseOutput(_ output: MLFeatureProvider) throws -> {output_return_type} {{
{output_parsing_body}
    }}
}}

// MARK: - Errors

enum PredictorError: LocalizedError {{
    case modelNotFound(String)
    case invalidImage
    case pixelBufferCreationFailed
    case outputMissing(String)
    case multiArrayCreationFailed

    var errorDescription: String? {{
        switch self {{
        case .modelNotFound(let name):
            return "Core ML model not found in bundle: \\(name)"
        case .invalidImage:
            return "Could not extract CGImage from the provided UIImage"
        case .pixelBufferCreationFailed:
            return "Failed to create CVPixelBuffer for model input"
        case .outputMissing(let name):
            return "Expected output '\\(name)' not found in model prediction"
        case .multiArrayCreationFailed:
            return "Failed to create MLMultiArray for model input"
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (NMS stripped)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_NMS_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Post-processing for detection models where NMS was stripped during conversion.
/// Takes raw model output tensors and returns filtered detections.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let detections = {class_name}PostProcessor.process(
///       outputs: raw,
///       confidenceThreshold: 0.25,
///       iouThreshold: 0.45
///   )

// MARK: - Detection result

/// A single detected object with bounding box, class, and confidence.
struct Detection {{
    /// Bounding box in normalized coordinates [0, 1] relative to input image.
    let bbox: CGRect
    /// Detected class index.
    let classIndex: Int
    /// Confidence score for this detection.
    let confidence: Float

    /// Center-x in normalized coordinates.
    var cx: CGFloat {{ bbox.midX }}
    /// Center-y in normalized coordinates.
    var cy: CGFloat {{ bbox.midY }}
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    // MARK: - Public API

    /// Decode raw model outputs into filtered detections.
    ///
    /// - Parameters:
    ///   - outputs: Dictionary of output name -> MLMultiArray from the predictor.
    ///   - confidenceThreshold: Minimum confidence to keep a detection (default 0.25).
    ///   - iouThreshold: IoU threshold for NMS merging (default 0.45).
    ///   - maxDetections: Maximum number of detections to return (default 100).
    /// - Returns: An array of `Detection` objects sorted by confidence (descending).
    static func process(
        outputs: [String: MLMultiArray],
        confidenceThreshold: Float = 0.25,
        iouThreshold: Float = 0.45,
        maxDetections: Int = 100
    ) -> [Detection] {{
        // Attempt to find the primary output tensor.
        // Detection models typically output a tensor of shape [1, N, C] or [1, C, N]
        // where N = number of candidate boxes, C = 4 (bbox) + num_classes.
        guard let tensor = outputs.values.first else {{
            return []
        }}

        let shape = (0..<tensor.shape.count).map {{ tensor.shape[$0].intValue }}
        guard shape.count >= 2 else {{ return [] }}

        // Determine layout
        let candidates: [Detection]
        if shape.count == 3 {{
            // [batch, candidates, attrs] or [batch, attrs, candidates]
            let dim1 = shape[1]
            let dim2 = shape[2]
            if dim2 > dim1 {{
                // [1, attrs, candidates] — transpose layout (e.g. YOLOv8)
                candidates = decodeTransposed(tensor: tensor, attrs: dim1, numCandidates: dim2, threshold: confidenceThreshold)
            }} else {{
                // [1, candidates, attrs] — standard layout
                candidates = decodeStandard(tensor: tensor, numCandidates: dim1, attrs: dim2, threshold: confidenceThreshold)
            }}
        }} else if shape.count == 2 {{
            // [candidates, attrs]
            candidates = decodeStandard2D(tensor: tensor, numCandidates: shape[0], attrs: shape[1], threshold: confidenceThreshold)
        }} else {{
            return []
        }}

        // Apply Non-Maximum Suppression
        let nmsResults = nonMaxSuppression(detections: candidates, iouThreshold: iouThreshold)

        // Limit to maxDetections, already sorted by confidence
        return Array(nmsResults.prefix(maxDetections))
    }}

    // MARK: - Decoding helpers

    /// Decode [1, candidates, attrs] layout.
    /// attrs = [cx, cy, w, h, class_scores...]
    private static func decodeStandard(
        tensor: MLMultiArray,
        numCandidates: Int,
        attrs: Int,
        threshold: Float
    ) -> [Detection] {{
        let numClasses = attrs - 4
        guard numClasses > 0 else {{ return [] }}

        var results: [Detection] = []
        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)

        for i in 0..<numCandidates {{
            let base = i * attrs

            // Find best class
            var bestClass = 0
            var bestScore: Float = -1
            for c in 0..<numClasses {{
                let score = ptr[base + 4 + c]
                if score > bestScore {{
                    bestScore = score
                    bestClass = c
                }}
            }}

            guard bestScore >= threshold else {{ continue }}

            // Decode bbox: [cx, cy, w, h] -> CGRect
            let cx = CGFloat(ptr[base + 0])
            let cy = CGFloat(ptr[base + 1])
            let w  = CGFloat(ptr[base + 2])
            let h  = CGFloat(ptr[base + 3])
            let rect = CGRect(x: cx - w / 2, y: cy - h / 2, width: w, height: h)

            results.append(Detection(bbox: rect, classIndex: bestClass, confidence: bestScore))
        }}

        return results
    }}

    /// Decode [1, attrs, candidates] layout (transposed, e.g. YOLOv8).
    /// Row 0..3 = cx, cy, w, h; rows 4.. = class scores.
    private static func decodeTransposed(
        tensor: MLMultiArray,
        attrs: Int,
        numCandidates: Int,
        threshold: Float
    ) -> [Detection] {{
        let numClasses = attrs - 4
        guard numClasses > 0 else {{ return [] }}

        var results: [Detection] = []
        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)

        for i in 0..<numCandidates {{
            // In transposed layout, element [row][col] = ptr[row * numCandidates + col]
            var bestClass = 0
            var bestScore: Float = -1
            for c in 0..<numClasses {{
                let score = ptr[(4 + c) * numCandidates + i]
                if score > bestScore {{
                    bestScore = score
                    bestClass = c
                }}
            }}

            guard bestScore >= threshold else {{ continue }}

            let cx = CGFloat(ptr[0 * numCandidates + i])
            let cy = CGFloat(ptr[1 * numCandidates + i])
            let w  = CGFloat(ptr[2 * numCandidates + i])
            let h  = CGFloat(ptr[3 * numCandidates + i])
            let rect = CGRect(x: cx - w / 2, y: cy - h / 2, width: w, height: h)

            results.append(Detection(bbox: rect, classIndex: bestClass, confidence: bestScore))
        }}

        return results
    }}

    /// Decode 2D [candidates, attrs] layout (no batch dimension).
    private static func decodeStandard2D(
        tensor: MLMultiArray,
        numCandidates: Int,
        attrs: Int,
        threshold: Float
    ) -> [Detection] {{
        // Reuse the standard decoder — memory layout is equivalent
        return decodeStandard(tensor: tensor, numCandidates: numCandidates, attrs: attrs, threshold: threshold)
    }}

    // MARK: - Non-Maximum Suppression

    /// Greedy NMS: keep highest-confidence detection and remove overlapping boxes.
    private static func nonMaxSuppression(
        detections: [Detection],
        iouThreshold: Float
    ) -> [Detection] {{
        // Sort by confidence descending
        let sorted = detections.sorted {{ $0.confidence > $1.confidence }}
        var kept: [Detection] = []
        var suppressed = Set<Int>()

        for i in 0..<sorted.count {{
            guard !suppressed.contains(i) else {{ continue }}
            let a = sorted[i]
            kept.append(a)

            for j in (i + 1)..<sorted.count {{
                guard !suppressed.contains(j) else {{ continue }}
                let b = sorted[j]
                if iou(a.bbox, b.bbox) > CGFloat(iouThreshold) {{
                    suppressed.insert(j)
                }}
            }}
        }}

        return kept
    }}

    /// Compute Intersection-over-Union for two CGRects.
    private static func iou(_ a: CGRect, _ b: CGRect) -> CGFloat {{
        let intersection = a.intersection(b)
        guard !intersection.isNull else {{ return 0 }}
        let intersectionArea = intersection.width * intersection.height
        let unionArea = a.width * a.height + b.width * b.height - intersectionArea
        guard unionArea > 0 else {{ return 0 }}
        return intersectionArea / unionArea
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (simple output parser, no NMS)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_SIMPLE_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Simple output parser for the converted Core ML model.
/// Extracts and organizes model output tensors into a structured form.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let parsed = {class_name}PostProcessor.process(outputs: raw)

// MARK: - Model output

/// Parsed model output with named arrays for convenient access.
struct {class_name}Output {{
{output_struct_fields}

    /// Access any output by name.
    let rawOutputs: [String: MLMultiArray]
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    /// Parse raw model outputs into a structured result.
    ///
    /// - Parameter outputs: Dictionary of output name -> MLMultiArray from the predictor.
    /// - Returns: A structured `{class_name}Output` containing all output tensors.
    static func process(outputs: [String: MLMultiArray]) -> {class_name}Output {{
        return {class_name}Output(
{output_struct_init_args}
            rawOutputs: outputs
        )
    }}
}}
"""


# ---------------------------------------------------------------------------
# Code generation logic
# ---------------------------------------------------------------------------


def _build_output_parsing_body(outputs: list[dict[str, Any]]) -> str:
    """Generate the body of parseOutput() for the predictor."""
    lines: list[str] = []
    lines.append("        var results: [String: MLMultiArray] = [:]")
    for out in outputs:
        name = out["name"]
        lines.append(f'        guard let {_swift_var(name)} = output.featureValue(for: "{name}")?.multiArrayValue else {{')
        lines.append(f'            throw PredictorError.outputMissing("{name}")')
        lines.append("        }")
        lines.append(f'        results["{name}"] = {_swift_var(name)}')
    lines.append("        return results")
    return "\n".join(lines)


def _swift_var(name: str) -> str:
    """Convert an output name to a valid Swift variable name (camelCase)."""
    cleaned = re.sub(r"[^a-zA-Z0-9]", "_", name)
    parts = [p for p in cleaned.split("_") if p]
    if not parts:
        return "output"
    result = parts[0].lower()
    for p in parts[1:]:
        result += p[0].upper() + p[1:]
    return result


def _build_output_name_constants(outputs: list[dict[str, Any]]) -> str:
    """Generate static let constants for output tensor names."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        lines.append(f'    static let outputName{var[0].upper() + var[1:]} = "{name}"')
    return "\n".join(lines)


def _build_output_struct_fields(outputs: list[dict[str, Any]]) -> str:
    """Generate struct fields for the simple output parser."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        shape_comment = ""
        if "shape" in out and out["shape"]:
            shape_comment = f"  // shape: {out['shape']}"
        lines.append(f"    let {var}: MLMultiArray?{shape_comment}")
    return "\n".join(lines)


def _build_output_struct_init_args(outputs: list[dict[str, Any]]) -> str:
    """Generate init arguments for the simple output struct."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        lines.append(f'            {var}: outputs["{name}"],')
    return "\n".join(lines)


def generate_swift_code(
    coreml_path: str,
    model_name: str,
    recipe_results: list | None = None,
) -> dict[str, str]:
    """Generate Swift code files for a Core ML model.

    Reads the model spec to understand inputs/outputs, then produces
    ready-to-use Swift source files.

    Args:
        coreml_path: Path to the .mlpackage directory.
        model_name: Human-readable model name (used for class naming).
        recipe_results: List of RecipeResult objects from conversion (to detect NMS stripping).

    Returns:
        Dictionary mapping filename to Swift source code content.
    """
    spec = _load_spec(coreml_path)
    description = spec.description

    # Analyze inputs
    inputs = [_describe_input(inp) for inp in description.input]
    outputs = [_describe_output(out) for out in description.output]

    if not inputs:
        logger.warning("Model has no inputs; skipping code generation")
        return {}

    class_name = _sanitize_swift_name(model_name)
    raw_model_name = Path(coreml_path).stem  # filename without extension

    # Determine primary input type
    primary_input = inputs[0]
    is_image_input = primary_input["kind"] == "image"

    # Build output parsing body (shared between templates)
    output_return_type = "[String: MLMultiArray]"
    output_body = _build_output_parsing_body(outputs)

    files: dict[str, str] = {}

    # --- Generate Predictor.swift ---
    if is_image_input:
        predictor_code = _PREDICTOR_IMAGE_TEMPLATE.format(
            class_name=class_name,
            model_name=raw_model_name,
            input_name=primary_input["name"],
            input_width=primary_input.get("width", 640),
            input_height=primary_input.get("height", 640),
            output_return_type=output_return_type,
            output_parsing_body=output_body,
        )
    else:
        # MultiArray input
        shape = primary_input.get("shape", [1, 3, 640, 640])
        shape_literal = "[" + ", ".join(str(s) for s in shape) + "]"
        shape_comment = "[" + ", ".join(str(s) for s in shape) + "]"

        predictor_code = _PREDICTOR_MULTIARRAY_TEMPLATE.format(
            class_name=class_name,
            model_name=raw_model_name,
            input_name=primary_input["name"],
            input_shape_literal=shape_literal,
            input_shape_comment=shape_comment,
            output_return_type=output_return_type,
            output_parsing_body=output_body,
        )

    files[f"{class_name}Predictor.swift"] = predictor_code

    # --- Generate PostProcessor.swift ---
    nms_stripped = _has_nms_stripped(recipe_results)
    output_name_constants = _build_output_name_constants(outputs)

    if nms_stripped:
        postprocessor_code = _POSTPROCESSOR_NMS_TEMPLATE.format(
            class_name=class_name,
            output_name_constants=output_name_constants,
        )
    else:
        output_struct_fields = _build_output_struct_fields(outputs)
        output_struct_init_args = _build_output_struct_init_args(outputs)

        postprocessor_code = _POSTPROCESSOR_SIMPLE_TEMPLATE.format(
            class_name=class_name,
            output_name_constants=output_name_constants,
            output_struct_fields=output_struct_fields,
            output_struct_init_args=output_struct_init_args,
        )

    files[f"{class_name}PostProcessor.swift"] = postprocessor_code

    return files


def save_swift_code(
    coreml_path: str,
    model_name: str,
    output_dir: Path,
    recipe_results: list | None = None,
) -> list[Path]:
    """Generate and save Swift files to output_dir.

    Args:
        coreml_path: Path to the .mlpackage directory.
        model_name: Human-readable model name (used for class naming).
        output_dir: Directory to write generated Swift files into.
        recipe_results: List of RecipeResult objects from conversion.

    Returns:
        List of Path objects for each generated file.
    """
    files = generate_swift_code(coreml_path, model_name, recipe_results)

    if not files:
        logger.warning("No Swift code generated")
        return []

    output_dir.mkdir(parents=True, exist_ok=True)
    saved: list[Path] = []

    for filename, content in files.items():
        path = output_dir / filename
        path.write_text(content, encoding="utf-8")
        saved.append(path)
        logger.info("Generated Swift file: %s", path)

    return saved
