"""Swift inference code generation for Core ML models.

Reads the Core ML model spec to understand inputs/outputs, then generates
production-ready Swift files that users can drop into an Xcode project.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import coremltools as ct

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Model spec introspection
# ---------------------------------------------------------------------------


def _sanitize_swift_name(name: str) -> str:
    """Convert a raw model name into a valid Swift identifier (PascalCase)."""
    # Strip extension and path
    name = Path(name).stem
    # Replace non-alphanumeric chars with underscores
    name = re.sub(r"[^a-zA-Z0-9]", "_", name)
    # PascalCase: split on underscores and capitalize each word
    parts = [p for p in name.split("_") if p]
    if not parts:
        return "Model"
    return "".join(p[0].upper() + p[1:] for p in parts)


def _load_spec(coreml_path: str) -> Any:
    """Load the Core ML model spec without loading weights."""
    model = ct.models.MLModel(coreml_path, skip_model_load=True)
    return model.get_spec()


def _describe_input(feature: Any) -> dict[str, Any]:
    """Extract input metadata from a feature description proto."""
    info: dict[str, Any] = {"name": feature.name}
    ftype = feature.type

    if ftype.HasField("imageType"):
        img = ftype.imageType
        info["kind"] = "image"
        info["width"] = img.width
        info["height"] = img.height
        # colorSpace: 10=RGB, 20=BGR, 30=GRAYSCALE
        info["channels"] = 1 if img.colorSpace == 30 else 3
    elif ftype.HasField("multiArrayType"):
        ma = ftype.multiArrayType
        info["kind"] = "multiarray"
        info["shape"] = list(ma.shape)
        # dataType: 65568=FLOAT32, 65552=FLOAT16, 131104=INT32
        info["dtype"] = "Float32"
    else:
        info["kind"] = "unknown"
    return info


def _describe_output(feature: Any) -> dict[str, Any]:
    """Extract output metadata from a feature description proto."""
    info: dict[str, Any] = {"name": feature.name}
    ftype = feature.type

    if ftype.HasField("multiArrayType"):
        ma = ftype.multiArrayType
        info["kind"] = "multiarray"
        info["shape"] = list(ma.shape)
    elif ftype.HasField("imageType"):
        info["kind"] = "image"
    elif ftype.HasField("dictionaryType"):
        info["kind"] = "dictionary"
    else:
        info["kind"] = "unknown"
    return info


def _has_nms_stripped(recipe_results: list[Any] | None) -> bool:
    """Check if NMS was stripped during conversion."""
    if not recipe_results:
        return False
    for r in recipe_results:
        name = getattr(r, "recipe_name", "") if hasattr(r, "recipe_name") else str(r)
        if "nms" in name.lower() or "detection_unwrap" in name.lower():
            return True
    return False


# ---------------------------------------------------------------------------
# Swift template: Predictor (image input)
# ---------------------------------------------------------------------------

_PREDICTOR_IMAGE_TEMPLATE = """\
import CoreML
import Vision
import UIKit

/// Auto-generated by Model2Mobile
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let results = try predictor.predict(image: uiImage)
///
/// Requirements:
///   - Add {model_name}.mlpackage to your Xcode project
///   - iOS 15.0+ / macOS 12.0+
class {class_name}Predictor {{

    // MARK: - Properties

    private let model: MLModel

    /// Input image will be resized to this dimension.
    let inputWidth: Int = {input_width}
    let inputHeight: Int = {input_height}

    // MARK: - Initialization

    /// Load the Core ML model with the specified compute units.
    /// - Parameter computeUnits: Which hardware to run inference on (default: `.all`).
    init(computeUnits: MLComputeUnits = .all) throws {{
        let config = MLModelConfiguration()
        config.computeUnits = computeUnits

        // Load the compiled model from the app bundle.
        // Make sure {model_name}.mlpackage is added to your Xcode target.
        guard let modelURL = Bundle.main.url(
            forResource: "{model_name}",
            withExtension: "mlmodelc"
        ) else {{
            throw PredictorError.modelNotFound("{model_name}.mlmodelc")
        }}
        self.model = try MLModel(contentsOf: modelURL, configuration: config)
    }}

    // MARK: - Prediction

    /// Run inference on a UIImage.
    /// - Parameter image: The input image (any size; will be resized automatically).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(image: UIImage) throws -> {output_return_type} {{
        guard let cgImage = image.cgImage else {{
            throw PredictorError.invalidImage
        }}

        let pixelBuffer = try createPixelBuffer(from: cgImage)
        return try predict(pixelBuffer: pixelBuffer)
    }}

    /// Run inference on a CVPixelBuffer.
    /// - Parameter pixelBuffer: A pixel buffer sized to (inputWidth x inputHeight).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(pixelBuffer: CVPixelBuffer) throws -> {output_return_type} {{
        let input = try MLDictionaryFeatureProvider(
            dictionary: ["{input_name}": MLFeatureValue(pixelBuffer: pixelBuffer)]
        )

        let output = try model.prediction(from: input)
        return try parseOutput(output)
    }}

    // MARK: - Preprocessing

    /// Resize a CGImage and convert it to a CVPixelBuffer suitable for the model.
    private func createPixelBuffer(from cgImage: CGImage) throws -> CVPixelBuffer {{
        var pixelBuffer: CVPixelBuffer?
        let attrs: [String: Any] = [
            kCVPixelBufferCGImageCompatibilityKey as String: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey as String: true,
        ]

        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            inputWidth,
            inputHeight,
            kCVPixelFormatType_32BGRA,
            attrs as CFDictionary,
            &pixelBuffer
        )

        guard status == kCVReturnSuccess, let buffer = pixelBuffer else {{
            throw PredictorError.pixelBufferCreationFailed
        }}

        CVPixelBufferLockBaseAddress(buffer, [])
        defer {{ CVPixelBufferUnlockBaseAddress(buffer, []) }}

        guard let context = CGContext(
            data: CVPixelBufferGetBaseAddress(buffer),
            width: inputWidth,
            height: inputHeight,
            bitsPerComponent: 8,
            bytesPerRow: CVPixelBufferGetBytesPerRow(buffer),
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue
                | CGBitmapInfo.byteOrder32Little.rawValue
        ) else {{
            throw PredictorError.pixelBufferCreationFailed
        }}

        // Draw the image scaled to the model's expected input size
        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: inputWidth, height: inputHeight))

        return buffer
    }}

    // MARK: - Output parsing

    private func parseOutput(_ output: MLFeatureProvider) throws -> {output_return_type} {{
{output_parsing_body}
    }}
}}

// MARK: - Errors

enum PredictorError: LocalizedError {{
    case modelNotFound(String)
    case invalidImage
    case pixelBufferCreationFailed
    case outputMissing(String)
    case multiArrayCreationFailed

    var errorDescription: String? {{
        switch self {{
        case .modelNotFound(let name):
            return "Core ML model not found in bundle: \\(name)"
        case .invalidImage:
            return "Could not extract CGImage from the provided UIImage"
        case .pixelBufferCreationFailed:
            return "Failed to create CVPixelBuffer for model input"
        case .outputMissing(let name):
            return "Expected output '\\(name)' not found in model prediction"
        case .multiArrayCreationFailed:
            return "Failed to create MLMultiArray for model input"
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: Predictor (multiarray input)
# ---------------------------------------------------------------------------

_PREDICTOR_MULTIARRAY_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let inputArray: MLMultiArray = ...  // shape: {input_shape_comment}
///   let results = try predictor.predict(input: inputArray)
///
/// Requirements:
///   - Add {model_name}.mlpackage to your Xcode project
///   - iOS 15.0+ / macOS 12.0+
class {class_name}Predictor {{

    // MARK: - Properties

    private let model: MLModel

    /// Expected input shape: {input_shape_comment}
    let inputShape: [Int] = {input_shape_literal}

    // MARK: - Initialization

    /// Load the Core ML model with the specified compute units.
    /// - Parameter computeUnits: Which hardware to run inference on (default: `.all`).
    init(computeUnits: MLComputeUnits = .all) throws {{
        let config = MLModelConfiguration()
        config.computeUnits = computeUnits

        guard let modelURL = Bundle.main.url(
            forResource: "{model_name}",
            withExtension: "mlmodelc"
        ) else {{
            throw PredictorError.modelNotFound("{model_name}.mlmodelc")
        }}
        self.model = try MLModel(contentsOf: modelURL, configuration: config)
    }}

    // MARK: - Prediction

    /// Run inference on an MLMultiArray input.
    /// - Parameter input: Multi-dimensional array matching the expected input shape.
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(input: MLMultiArray) throws -> {output_return_type} {{
        let featureValue = MLFeatureValue(multiArray: input)
        let inputProvider = try MLDictionaryFeatureProvider(
            dictionary: ["{input_name}": featureValue]
        )

        let output = try model.prediction(from: inputProvider)
        return try parseOutput(output)
    }}

    /// Convenience: run inference from a UIImage by converting it to a normalized tensor.
    /// - Parameter image: The input image (will be resized to model input dimensions).
    /// - Returns: A dictionary mapping output names to their MLMultiArray values.
    func predict(image: UIImage) throws -> {output_return_type} {{
        let inputArray = try imageToMultiArray(image)
        return try predict(input: inputArray)
    }}

    // MARK: - Image to MLMultiArray conversion

    /// Convert a UIImage to a normalized MLMultiArray [1, C, H, W].
    private func imageToMultiArray(_ image: UIImage) throws -> MLMultiArray {{
        guard inputShape.count == 4 else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        let channels = inputShape[1]
        let height = inputShape[2]
        let width = inputShape[3]

        guard let cgImage = image.cgImage else {{
            throw PredictorError.invalidImage
        }}

        // Render the image into a raw RGBA byte buffer
        let bytesPerPixel = 4
        let bytesPerRow = bytesPerPixel * width
        var rawBytes = [UInt8](repeating: 0, count: height * bytesPerRow)

        guard let context = CGContext(
            data: &rawBytes,
            width: width,
            height: height,
            bitsPerComponent: 8,
            bytesPerRow: bytesPerRow,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: width, height: height))

        // Create the MLMultiArray in NCHW layout
        let shape = inputShape.map {{ NSNumber(value: $0) }}
        guard let array = try? MLMultiArray(shape: shape, dataType: .float32) else {{
            throw PredictorError.multiArrayCreationFailed
        }}

        // Fill: normalize pixel values to [0, 1]
        let channelCount = min(channels, 3)
        for c in 0..<channelCount {{
            for y in 0..<height {{
                for x in 0..<width {{
                    let pixelIndex = y * width + x
                    let byteOffset = pixelIndex * bytesPerPixel + c  // R=0, G=1, B=2
                    let value = Float(rawBytes[byteOffset]) / 255.0
                    let arrayIndex = c * height * width + y * width + x
                    array[arrayIndex] = NSNumber(value: value)
                }}
            }}
        }}

        return array
    }}

    // MARK: - Output parsing

    private func parseOutput(_ output: MLFeatureProvider) throws -> {output_return_type} {{
{output_parsing_body}
    }}
}}

// MARK: - Errors

enum PredictorError: LocalizedError {{
    case modelNotFound(String)
    case invalidImage
    case pixelBufferCreationFailed
    case outputMissing(String)
    case multiArrayCreationFailed

    var errorDescription: String? {{
        switch self {{
        case .modelNotFound(let name):
            return "Core ML model not found in bundle: \\(name)"
        case .invalidImage:
            return "Could not extract CGImage from the provided UIImage"
        case .pixelBufferCreationFailed:
            return "Failed to create CVPixelBuffer for model input"
        case .outputMissing(let name):
            return "Expected output '\\(name)' not found in model prediction"
        case .multiArrayCreationFailed:
            return "Failed to create MLMultiArray for model input"
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (NMS stripped)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_NMS_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Post-processing for detection models where NMS was stripped during conversion.
/// Takes raw model output tensors and returns filtered detections.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let detections = {class_name}PostProcessor.process(
///       outputs: raw,
///       confidenceThreshold: 0.25,
///       iouThreshold: 0.45
///   )

// MARK: - Detection result

/// A single detected object with bounding box, class, and confidence.
struct Detection {{
    /// Bounding box in normalized coordinates [0, 1] relative to input image.
    let bbox: CGRect
    /// Detected class index.
    let classIndex: Int
    /// Confidence score for this detection.
    let confidence: Float

    /// Center-x in normalized coordinates.
    var cx: CGFloat {{ bbox.midX }}
    /// Center-y in normalized coordinates.
    var cy: CGFloat {{ bbox.midY }}
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    // MARK: - Public API

    /// Decode raw model outputs into filtered detections.
    ///
    /// - Parameters:
    ///   - outputs: Dictionary of output name -> MLMultiArray from the predictor.
    ///   - confidenceThreshold: Minimum confidence to keep a detection (default 0.25).
    ///   - iouThreshold: IoU threshold for NMS merging (default 0.45).
    ///   - maxDetections: Maximum number of detections to return (default 100).
    /// - Returns: An array of `Detection` objects sorted by confidence (descending).
    static func process(
        outputs: [String: MLMultiArray],
        confidenceThreshold: Float = 0.25,
        iouThreshold: Float = 0.45,
        maxDetections: Int = 100
    ) -> [Detection] {{
        // Attempt to find the primary output tensor.
        // Detection models typically output a tensor of shape [1, N, C] or [1, C, N]
        // where N = number of candidate boxes, C = 4 (bbox) + num_classes.
        guard let tensor = outputs.values.first else {{
            return []
        }}

        let shape = (0..<tensor.shape.count).map {{ tensor.shape[$0].intValue }}
        guard shape.count >= 2 else {{ return [] }}

        // Determine layout
        let candidates: [Detection]
        if shape.count == 3 {{
            // [batch, candidates, attrs] or [batch, attrs, candidates]
            let dim1 = shape[1]
            let dim2 = shape[2]
            if dim2 > dim1 {{
                // [1, attrs, candidates] — transpose layout (e.g. YOLOv8)
                candidates = decodeTransposed(tensor: tensor, attrs: dim1, numCandidates: dim2, threshold: confidenceThreshold)
            }} else {{
                // [1, candidates, attrs] — standard layout
                candidates = decodeStandard(tensor: tensor, numCandidates: dim1, attrs: dim2, threshold: confidenceThreshold)
            }}
        }} else if shape.count == 2 {{
            // [candidates, attrs]
            candidates = decodeStandard2D(tensor: tensor, numCandidates: shape[0], attrs: shape[1], threshold: confidenceThreshold)
        }} else {{
            return []
        }}

        // Apply Non-Maximum Suppression
        let nmsResults = nonMaxSuppression(detections: candidates, iouThreshold: iouThreshold)

        // Limit to maxDetections, already sorted by confidence
        return Array(nmsResults.prefix(maxDetections))
    }}

    // MARK: - Decoding helpers

    /// Decode [1, candidates, attrs] layout.
    /// attrs = [cx, cy, w, h, class_scores...]
    private static func decodeStandard(
        tensor: MLMultiArray,
        numCandidates: Int,
        attrs: Int,
        threshold: Float
    ) -> [Detection] {{
        let numClasses = attrs - 4
        guard numClasses > 0 else {{ return [] }}

        var results: [Detection] = []
        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)

        for i in 0..<numCandidates {{
            let base = i * attrs

            // Find best class
            var bestClass = 0
            var bestScore: Float = -1
            for c in 0..<numClasses {{
                let score = ptr[base + 4 + c]
                if score > bestScore {{
                    bestScore = score
                    bestClass = c
                }}
            }}

            guard bestScore >= threshold else {{ continue }}

            // Decode bbox: [cx, cy, w, h] -> CGRect
            let cx = CGFloat(ptr[base + 0])
            let cy = CGFloat(ptr[base + 1])
            let w  = CGFloat(ptr[base + 2])
            let h  = CGFloat(ptr[base + 3])
            let rect = CGRect(x: cx - w / 2, y: cy - h / 2, width: w, height: h)

            results.append(Detection(bbox: rect, classIndex: bestClass, confidence: bestScore))
        }}

        return results
    }}

    /// Decode [1, attrs, candidates] layout (transposed, e.g. YOLOv8).
    /// Row 0..3 = cx, cy, w, h; rows 4.. = class scores.
    private static func decodeTransposed(
        tensor: MLMultiArray,
        attrs: Int,
        numCandidates: Int,
        threshold: Float
    ) -> [Detection] {{
        let numClasses = attrs - 4
        guard numClasses > 0 else {{ return [] }}

        var results: [Detection] = []
        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)

        for i in 0..<numCandidates {{
            // In transposed layout, element [row][col] = ptr[row * numCandidates + col]
            var bestClass = 0
            var bestScore: Float = -1
            for c in 0..<numClasses {{
                let score = ptr[(4 + c) * numCandidates + i]
                if score > bestScore {{
                    bestScore = score
                    bestClass = c
                }}
            }}

            guard bestScore >= threshold else {{ continue }}

            let cx = CGFloat(ptr[0 * numCandidates + i])
            let cy = CGFloat(ptr[1 * numCandidates + i])
            let w  = CGFloat(ptr[2 * numCandidates + i])
            let h  = CGFloat(ptr[3 * numCandidates + i])
            let rect = CGRect(x: cx - w / 2, y: cy - h / 2, width: w, height: h)

            results.append(Detection(bbox: rect, classIndex: bestClass, confidence: bestScore))
        }}

        return results
    }}

    /// Decode 2D [candidates, attrs] layout (no batch dimension).
    private static func decodeStandard2D(
        tensor: MLMultiArray,
        numCandidates: Int,
        attrs: Int,
        threshold: Float
    ) -> [Detection] {{
        // Reuse the standard decoder — memory layout is equivalent
        return decodeStandard(tensor: tensor, numCandidates: numCandidates, attrs: attrs, threshold: threshold)
    }}

    // MARK: - Non-Maximum Suppression

    /// Greedy NMS: keep highest-confidence detection and remove overlapping boxes.
    private static func nonMaxSuppression(
        detections: [Detection],
        iouThreshold: Float
    ) -> [Detection] {{
        // Sort by confidence descending
        let sorted = detections.sorted {{ $0.confidence > $1.confidence }}
        var kept: [Detection] = []
        var suppressed = Set<Int>()

        for i in 0..<sorted.count {{
            guard !suppressed.contains(i) else {{ continue }}
            let a = sorted[i]
            kept.append(a)

            for j in (i + 1)..<sorted.count {{
                guard !suppressed.contains(j) else {{ continue }}
                let b = sorted[j]
                if iou(a.bbox, b.bbox) > CGFloat(iouThreshold) {{
                    suppressed.insert(j)
                }}
            }}
        }}

        return kept
    }}

    /// Compute Intersection-over-Union for two CGRects.
    private static func iou(_ a: CGRect, _ b: CGRect) -> CGFloat {{
        let intersection = a.intersection(b)
        guard !intersection.isNull else {{ return 0 }}
        let intersectionArea = intersection.width * intersection.height
        let unionArea = a.width * a.height + b.width * b.height - intersectionArea
        guard unionArea > 0 else {{ return 0 }}
        return intersectionArea / unionArea
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (simple output parser, no NMS)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_SIMPLE_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Simple output parser for the converted Core ML model.
/// Extracts and organizes model output tensors into a structured form.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let parsed = {class_name}PostProcessor.process(outputs: raw)

// MARK: - Model output

/// Parsed model output with named arrays for convenient access.
struct {class_name}Output {{
{output_struct_fields}

    /// Access any output by name.
    let rawOutputs: [String: MLMultiArray]
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    /// Parse raw model outputs into a structured result.
    ///
    /// - Parameter outputs: Dictionary of output name -> MLMultiArray from the predictor.
    /// - Returns: A structured `{class_name}Output` containing all output tensors.
    static func process(outputs: [String: MLMultiArray]) -> {class_name}Output {{
        return {class_name}Output(
{output_struct_init_args}
            rawOutputs: outputs
        )
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (Classification)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_CLASSIFICATION_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Post-processing for classification models.
/// Takes raw model output logits or probabilities and returns top-K predictions.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let results = {class_name}PostProcessor.classify(
///       outputs: raw,
///       topK: 5,
///       labels: ["cat", "dog", ...]  // optional
///   )

// MARK: - Classification result

/// A single classification prediction with class index, confidence, and optional label.
struct ClassificationResult {{
    /// Index of the predicted class in the output tensor.
    let classIndex: Int
    /// Confidence score (probability) for this class.
    let confidence: Float
    /// Human-readable label, if a label list was provided.
    let label: String?
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    // MARK: - Public API

    /// Classify raw model outputs and return top-K predictions.
    ///
    /// - Parameters:
    ///   - outputs: Dictionary of output name -> MLMultiArray from the predictor.
    ///   - topK: Number of top predictions to return (default 5).
    ///   - labels: Optional array of class label strings indexed by class index.
    /// - Returns: An array of `ClassificationResult` sorted by confidence (descending).
    static func classify(
        outputs: [String: MLMultiArray],
        topK: Int = 5,
        labels: [String]? = nil
    ) -> [ClassificationResult] {{
        guard let tensor = outputs.values.first else {{
            return []
        }}

        let count = tensorElementCount(tensor)
        guard count > 0 else {{ return [] }}

        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)

        // Extract raw values
        var values = [Float](repeating: 0, count: count)
        for i in 0..<count {{
            values[i] = ptr[i]
        }}

        // Apply softmax if values are not already probabilities.
        // Heuristic: if any value is negative or any value > 1, treat as logits.
        let needsSoftmax = values.contains(where: {{ $0 < 0 || $0 > 1.0 }})
        if needsSoftmax {{
            values = softmax(values)
        }}

        // Build indexed pairs and sort descending by score
        let indexed = values.enumerated().map {{ (index: $0.offset, score: $0.element) }}
        let sorted = indexed.sorted {{ $0.score > $1.score }}

        // Take top-K
        let k = min(topK, sorted.count)
        return sorted.prefix(k).map {{ item in
            ClassificationResult(
                classIndex: item.index,
                confidence: item.score,
                label: labels.flatMap {{ $0.indices.contains(item.index) ? $0[item.index] : nil }}
            )
        }}
    }}

    // MARK: - Helpers

    /// Compute the total number of elements in an MLMultiArray.
    private static func tensorElementCount(_ tensor: MLMultiArray) -> Int {{
        var count = 1
        for i in 0..<tensor.shape.count {{
            let dim = tensor.shape[i].intValue
            // Skip batch dimensions of size 1 at the front
            if i == 0 && dim == 1 && tensor.shape.count > 1 {{
                continue
            }}
            count *= dim
        }}
        return count
    }}

    /// Apply the softmax function to an array of logits.
    private static func softmax(_ logits: [Float]) -> [Float] {{
        let maxVal = logits.max() ?? 0
        let exps = logits.map {{ exp($0 - maxVal) }}
        let sumExps = exps.reduce(0, +)
        guard sumExps > 0 else {{ return logits }}
        return exps.map {{ $0 / sumExps }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (Segmentation)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_SEGMENTATION_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Post-processing for segmentation models.
/// Takes raw model output (N, C, H, W) and produces a pixel-level class map
/// via argmax along the class dimension.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let result = {class_name}PostProcessor.segment(outputs: raw)
///   let maskImage = result.colorMask(palette: nil)

// MARK: - Segmentation result

/// Segmentation output containing a per-pixel class index map.
struct SegmentationResult {{
    /// 2D array of class indices, accessed as classMap[y][x].
    let classMap: [[Int]]
    /// Width of the segmentation map in pixels.
    let width: Int
    /// Height of the segmentation map in pixels.
    let height: Int
    /// Number of classes the model can predict.
    let numClasses: Int

    /// Render the class map as a color mask UIImage.
    ///
    /// - Parameter palette: Optional array of RGB tuples, one per class.
    ///   If nil, a default palette is generated automatically.
    /// - Returns: A UIImage of the color mask, or nil on failure.
    func colorMask(palette: [(UInt8, UInt8, UInt8)]? = nil) -> UIImage? {{
        let colors = palette ?? Self.defaultPalette(numClasses: numClasses)
        let bytesPerPixel = 4
        let bytesPerRow = bytesPerPixel * width
        var pixelData = [UInt8](repeating: 255, count: height * bytesPerRow)

        for y in 0..<height {{
            for x in 0..<width {{
                let classIdx = classMap[y][x]
                let safeIdx = classIdx < colors.count ? classIdx : 0
                let color = colors[safeIdx]
                let offset = y * bytesPerRow + x * bytesPerPixel
                pixelData[offset + 0] = color.0  // R
                pixelData[offset + 1] = color.1  // G
                pixelData[offset + 2] = color.2  // B
                pixelData[offset + 3] = 255      // A
            }}
        }}

        guard let provider = CGDataProvider(data: Data(pixelData) as CFData),
              let cgImage = CGImage(
                  width: width,
                  height: height,
                  bitsPerComponent: 8,
                  bitsPerPixel: 32,
                  bytesPerRow: bytesPerRow,
                  space: CGColorSpaceCreateDeviceRGB(),
                  bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
                  provider: provider,
                  decode: nil,
                  shouldInterpolate: false,
                  intent: .defaultIntent
              ) else {{
            return nil
        }}

        return UIImage(cgImage: cgImage)
    }}

    /// Generate a default color palette using evenly spaced hues.
    private static func defaultPalette(numClasses: Int) -> [(UInt8, UInt8, UInt8)] {{
        (0..<numClasses).map {{ i in
            let hue = CGFloat(i) / CGFloat(max(numClasses, 1))
            let color = UIColor(hue: hue, saturation: 0.8, brightness: 0.9, alpha: 1.0)
            var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0
            color.getRed(&r, green: &g, blue: &b, alpha: nil)
            return (UInt8(r * 255), UInt8(g * 255), UInt8(b * 255))
        }}
    }}
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    // MARK: - Public API

    /// Segment raw model outputs into a per-pixel class map.
    ///
    /// Expects the primary output tensor to have shape [N, C, H, W] where
    /// C is the number of classes. Performs argmax along the class dimension.
    ///
    /// - Parameter outputs: Dictionary of output name -> MLMultiArray from the predictor.
    /// - Returns: A `SegmentationResult` containing the class map and metadata.
    static func segment(outputs: [String: MLMultiArray]) -> SegmentationResult {{
        guard let tensor = outputs.values.first else {{
            return SegmentationResult(classMap: [], width: 0, height: 0, numClasses: 0)
        }}

        let shape = (0..<tensor.shape.count).map {{ tensor.shape[$0].intValue }}

        // Determine C, H, W from the shape.
        // Support [C, H, W], [1, C, H, W], or [H, W] (single-class).
        let numClasses: Int
        let height: Int
        let width: Int
        let classStride: Int
        let heightStride: Int

        switch shape.count {{
        case 4:
            // [N, C, H, W]
            numClasses = shape[1]
            height = shape[2]
            width = shape[3]
            classStride = height * width
            heightStride = width
        case 3:
            // [C, H, W]
            numClasses = shape[0]
            height = shape[1]
            width = shape[2]
            classStride = height * width
            heightStride = width
        case 2:
            // [H, W] — already a class map (single class or pre-argmaxed)
            numClasses = 1
            height = shape[0]
            width = shape[1]
            classStride = 0
            heightStride = width
        default:
            return SegmentationResult(classMap: [], width: 0, height: 0, numClasses: 0)
        }}

        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)
        var classMap = [[Int]](repeating: [Int](repeating: 0, count: width), count: height)

        if numClasses <= 1 {{
            // Pre-argmaxed or single-class: round float values to int
            for y in 0..<height {{
                for x in 0..<width {{
                    let idx = y * heightStride + x
                    classMap[y][x] = Int(ptr[idx].rounded())
                }}
            }}
        }} else {{
            // Argmax along class dimension
            for y in 0..<height {{
                for x in 0..<width {{
                    var bestClass = 0
                    var bestScore: Float = -.greatestFiniteMagnitude
                    for c in 0..<numClasses {{
                        let offset: Int
                        if shape.count == 4 {{
                            offset = c * classStride + y * heightStride + x
                        }} else {{
                            offset = c * classStride + y * heightStride + x
                        }}
                        let score = ptr[offset]
                        if score > bestScore {{
                            bestScore = score
                            bestClass = c
                        }}
                    }}
                    classMap[y][x] = bestClass
                }}
            }}
        }}

        return SegmentationResult(
            classMap: classMap,
            width: width,
            height: height,
            numClasses: max(numClasses, 1)
        )
    }}
}}
"""


# ---------------------------------------------------------------------------
# Swift template: PostProcessor (Depth Estimation)
# ---------------------------------------------------------------------------

_POSTPROCESSOR_DEPTH_TEMPLATE = """\
import CoreML
import UIKit

/// Auto-generated by Model2Mobile
///
/// Post-processing for monocular depth estimation models.
/// Takes raw model output (N, 1, H, W) and produces a normalized depth map.
///
/// Usage:
///   let predictor = try {class_name}Predictor()
///   let raw = try predictor.predict(image: uiImage)
///   let result = {class_name}PostProcessor.depth(outputs: raw)
///   let depthImage = result.depthImage()

// MARK: - Depth result

/// Depth estimation output containing a per-pixel depth map.
struct DepthResult {{
    /// 2D array of depth values normalized to [0, 1], accessed as depthMap[y][x].
    let depthMap: [[Float]]
    /// Width of the depth map in pixels.
    let width: Int
    /// Height of the depth map in pixels.
    let height: Int
    /// Minimum raw depth value before normalization.
    let minDepth: Float
    /// Maximum raw depth value before normalization.
    let maxDepth: Float

    /// Render the depth map as a grayscale UIImage.
    ///
    /// Closer pixels are brighter (white), farther pixels are darker (black).
    ///
    /// - Returns: A grayscale UIImage, or nil on failure.
    func depthImage() -> UIImage? {{
        let bytesPerPixel = 4
        let bytesPerRow = bytesPerPixel * width
        var pixelData = [UInt8](repeating: 255, count: height * bytesPerRow)

        for y in 0..<height {{
            for x in 0..<width {{
                // Invert so near = bright, far = dark (common convention)
                let value = UInt8(clamping: Int((1.0 - depthMap[y][x]) * 255.0))
                let offset = y * bytesPerRow + x * bytesPerPixel
                pixelData[offset + 0] = value  // R
                pixelData[offset + 1] = value  // G
                pixelData[offset + 2] = value  // B
                pixelData[offset + 3] = 255    // A
            }}
        }}

        guard let provider = CGDataProvider(data: Data(pixelData) as CFData),
              let cgImage = CGImage(
                  width: width,
                  height: height,
                  bitsPerComponent: 8,
                  bitsPerPixel: 32,
                  bytesPerRow: bytesPerRow,
                  space: CGColorSpaceCreateDeviceRGB(),
                  bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
                  provider: provider,
                  decode: nil,
                  shouldInterpolate: false,
                  intent: .defaultIntent
              ) else {{
            return nil
        }}

        return UIImage(cgImage: cgImage)
    }}
}}

// MARK: - Post-processor

enum {class_name}PostProcessor {{

    /// Output tensor names produced by the model.
{output_name_constants}

    // MARK: - Public API

    /// Process raw model outputs into a normalized depth map.
    ///
    /// Expects the primary output tensor to have shape [N, 1, H, W], [1, H, W],
    /// or [H, W]. Normalizes depth values to [0, 1].
    ///
    /// - Parameter outputs: Dictionary of output name -> MLMultiArray from the predictor.
    /// - Returns: A `DepthResult` containing the normalized depth map and metadata.
    static func depth(outputs: [String: MLMultiArray]) -> DepthResult {{
        guard let tensor = outputs.values.first else {{
            return DepthResult(depthMap: [], width: 0, height: 0, minDepth: 0, maxDepth: 0)
        }}

        let shape = (0..<tensor.shape.count).map {{ tensor.shape[$0].intValue }}

        // Determine H, W from the shape.
        let height: Int
        let width: Int

        switch shape.count {{
        case 4:
            // [N, 1, H, W]
            height = shape[2]
            width = shape[3]
        case 3:
            // [1, H, W] or [C, H, W]
            height = shape[1]
            width = shape[2]
        case 2:
            // [H, W]
            height = shape[0]
            width = shape[1]
        default:
            return DepthResult(depthMap: [], width: 0, height: 0, minDepth: 0, maxDepth: 0)
        }}

        let ptr = tensor.dataPointer.assumingMemoryBound(to: Float.self)
        let totalPixels = height * width

        // First pass: find min and max depth values
        var minVal: Float = .greatestFiniteMagnitude
        var maxVal: Float = -.greatestFiniteMagnitude
        for i in 0..<totalPixels {{
            let v = ptr[i]
            if v < minVal {{ minVal = v }}
            if v > maxVal {{ maxVal = v }}
        }}

        let range = maxVal - minVal
        let safeRange = range > .ulpOfOne ? range : 1.0

        // Second pass: normalize to [0, 1] and build 2D array
        var depthMap = [[Float]](repeating: [Float](repeating: 0, count: width), count: height)

        for y in 0..<height {{
            for x in 0..<width {{
                let rawValue = ptr[y * width + x]
                depthMap[y][x] = (rawValue - minVal) / safeRange
            }}
        }}

        return DepthResult(
            depthMap: depthMap,
            width: width,
            height: height,
            minDepth: minVal,
            maxDepth: maxVal
        )
    }}
}}
"""


# ---------------------------------------------------------------------------
# Code generation logic
# ---------------------------------------------------------------------------


def _build_output_parsing_body(outputs: list[dict[str, Any]]) -> str:
    """Generate the body of parseOutput() for the predictor."""
    lines: list[str] = []
    lines.append("        var results: [String: MLMultiArray] = [:]")
    for out in outputs:
        name = out["name"]
        lines.append(f'        guard let {_swift_var(name)} = output.featureValue(for: "{name}")?.multiArrayValue else {{')
        lines.append(f'            throw PredictorError.outputMissing("{name}")')
        lines.append("        }")
        lines.append(f'        results["{name}"] = {_swift_var(name)}')
    lines.append("        return results")
    return "\n".join(lines)


def _swift_var(name: str) -> str:
    """Convert an output name to a valid Swift variable name (camelCase)."""
    cleaned = re.sub(r"[^a-zA-Z0-9]", "_", name)
    parts = [p for p in cleaned.split("_") if p]
    if not parts:
        return "output"
    result = parts[0].lower()
    for p in parts[1:]:
        result += p[0].upper() + p[1:]
    return result


def _build_output_name_constants(outputs: list[dict[str, Any]]) -> str:
    """Generate static let constants for output tensor names."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        lines.append(f'    static let outputName{var[0].upper() + var[1:]} = "{name}"')
    return "\n".join(lines)


def _build_output_struct_fields(outputs: list[dict[str, Any]]) -> str:
    """Generate struct fields for the simple output parser."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        shape_comment = ""
        if "shape" in out and out["shape"]:
            shape_comment = f"  // shape: {out['shape']}"
        lines.append(f"    let {var}: MLMultiArray?{shape_comment}")
    return "\n".join(lines)


def _build_output_struct_init_args(outputs: list[dict[str, Any]]) -> str:
    """Generate init arguments for the simple output struct."""
    lines: list[str] = []
    for out in outputs:
        name = out["name"]
        var = _swift_var(name)
        lines.append(f'            {var}: outputs["{name}"],')
    return "\n".join(lines)


def _generate_classification_postprocessor(
    class_name: str, outputs: list[dict[str, Any]]
) -> str:
    """Generate a classification PostProcessor Swift file."""
    output_name_constants = _build_output_name_constants(outputs)
    return _POSTPROCESSOR_CLASSIFICATION_TEMPLATE.format(
        class_name=class_name,
        output_name_constants=output_name_constants,
    )


def _generate_segmentation_postprocessor(
    class_name: str, outputs: list[dict[str, Any]]
) -> str:
    """Generate a segmentation PostProcessor Swift file."""
    output_name_constants = _build_output_name_constants(outputs)
    return _POSTPROCESSOR_SEGMENTATION_TEMPLATE.format(
        class_name=class_name,
        output_name_constants=output_name_constants,
    )


def _generate_depth_postprocessor(
    class_name: str, outputs: list[dict[str, Any]]
) -> str:
    """Generate a depth estimation PostProcessor Swift file."""
    output_name_constants = _build_output_name_constants(outputs)
    return _POSTPROCESSOR_DEPTH_TEMPLATE.format(
        class_name=class_name,
        output_name_constants=output_name_constants,
    )


def _generate_detection_postprocessor(
    class_name: str,
    outputs: list[dict[str, Any]],
    recipe_results: list[Any] | None,
) -> str:
    """Generate a detection PostProcessor Swift file (NMS or simple)."""
    output_name_constants = _build_output_name_constants(outputs)
    nms_stripped = _has_nms_stripped(recipe_results)

    if nms_stripped:
        return _POSTPROCESSOR_NMS_TEMPLATE.format(
            class_name=class_name,
            output_name_constants=output_name_constants,
        )
    else:
        output_struct_fields = _build_output_struct_fields(outputs)
        output_struct_init_args = _build_output_struct_init_args(outputs)

        return _POSTPROCESSOR_SIMPLE_TEMPLATE.format(
            class_name=class_name,
            output_name_constants=output_name_constants,
            output_struct_fields=output_struct_fields,
            output_struct_init_args=output_struct_init_args,
        )


def generate_swift_code(
    coreml_path: str,
    model_name: str,
    task: str = "detect",
    recipe_results: list | None = None,
) -> dict[str, str]:
    """Generate Swift code files for a Core ML model.

    Reads the model spec to understand inputs/outputs, then produces
    ready-to-use Swift source files tailored to the model's task.

    Args:
        coreml_path: Path to the .mlpackage directory.
        model_name: Human-readable model name (used for class naming).
        task: Model task type (``"detect"``, ``"classify"``, ``"segment"``, or ``"depth"``).
        recipe_results: List of RecipeResult objects from conversion (to detect NMS stripping).

    Returns:
        Dictionary mapping filename to Swift source code content.
    """
    spec = _load_spec(coreml_path)
    description = spec.description

    # Analyze inputs
    inputs = [_describe_input(inp) for inp in description.input]
    outputs = [_describe_output(out) for out in description.output]

    if not inputs:
        logger.warning("Model has no inputs; skipping code generation")
        return {}

    class_name = _sanitize_swift_name(model_name)
    raw_model_name = Path(coreml_path).stem  # filename without extension

    # Determine primary input type
    primary_input = inputs[0]
    is_image_input = primary_input["kind"] == "image"

    # Build output parsing body (shared between templates)
    output_return_type = "[String: MLMultiArray]"
    output_body = _build_output_parsing_body(outputs)

    files: dict[str, str] = {}

    # --- Generate Predictor.swift ---
    if is_image_input:
        predictor_code = _PREDICTOR_IMAGE_TEMPLATE.format(
            class_name=class_name,
            model_name=raw_model_name,
            input_name=primary_input["name"],
            input_width=primary_input.get("width", 640),
            input_height=primary_input.get("height", 640),
            output_return_type=output_return_type,
            output_parsing_body=output_body,
        )
    else:
        # MultiArray input
        shape = primary_input.get("shape", [1, 3, 640, 640])
        shape_literal = "[" + ", ".join(str(s) for s in shape) + "]"
        shape_comment = "[" + ", ".join(str(s) for s in shape) + "]"

        predictor_code = _PREDICTOR_MULTIARRAY_TEMPLATE.format(
            class_name=class_name,
            model_name=raw_model_name,
            input_name=primary_input["name"],
            input_shape_literal=shape_literal,
            input_shape_comment=shape_comment,
            output_return_type=output_return_type,
            output_parsing_body=output_body,
        )

    files[f"{class_name}Predictor.swift"] = predictor_code

    # --- Generate PostProcessor.swift (task-specific) ---
    if task == "classify":
        postprocessor_code = _generate_classification_postprocessor(class_name, outputs)
    elif task == "segment":
        postprocessor_code = _generate_segmentation_postprocessor(class_name, outputs)
    elif task == "depth":
        postprocessor_code = _generate_depth_postprocessor(class_name, outputs)
    else:
        # Default: detection (with NMS awareness)
        postprocessor_code = _generate_detection_postprocessor(
            class_name, outputs, recipe_results
        )

    files[f"{class_name}PostProcessor.swift"] = postprocessor_code

    return files


def save_swift_code(
    coreml_path: str,
    model_name: str,
    output_dir: Path,
    task: str = "detect",
    recipe_results: list | None = None,
) -> list[Path]:
    """Generate and save Swift files to output_dir.

    Args:
        coreml_path: Path to the .mlpackage directory.
        model_name: Human-readable model name (used for class naming).
        output_dir: Directory to write generated Swift files into.
        task: Model task type (``"detect"``, ``"classify"``, ``"segment"``, or ``"depth"``).
        recipe_results: List of RecipeResult objects from conversion.

    Returns:
        List of Path objects for each generated file.
    """
    files = generate_swift_code(coreml_path, model_name, task, recipe_results)

    if not files:
        logger.warning("No Swift code generated")
        return []

    output_dir.mkdir(parents=True, exist_ok=True)
    saved: list[Path] = []

    for filename, content in files.items():
        path = output_dir / filename
        path.write_text(content, encoding="utf-8")
        saved.append(path)
        logger.info("Generated Swift file: %s", path)

    return saved
